import { z } from 'zod';

/**
 * Zod Schema for **runtime validation** of the data required to create a user.
 * This is used in controllers or entry points to validate incoming request bodies.
 * The `user_id` is removed as it should be generated by the database, not provided by the client.
 */
export const CreateUserSchema = z.object({
  first_name: z.string().min(1, 'First name is required'),
  last_name: z.string().min(1, 'Last name is required'),
  email: z.string().email('A valid email is required'),
  password: z.string().min(8, 'Password must be at least 8 characters long'),
  profile: z.string().optional(), // Use .optional() to align with entity properties that can be undefined.
  role: z.enum(['patient', 'responder', 'admin', 'certifier']),
  bio_data_id: z.number().optional(),
  contact_data_id: z.number().optional(),
  cert_id: z.number().optional(),
});

/**
 * TypeScript type inferred from the Zod schema.
 * This provides **compile-time** type safety and is used in your use cases and repositories.
 */
export type CreateUserDTO = z.infer<typeof CreateUserSchema>;
